A comprehensive interactive Jupyter notebook demonstrating NumPy fundamentals through a practical student marks management system. This educational project covers array operations, statistical analysis, and data manipulation using real-world scenarios.

In [2]:
import numpy as np

Module 1

In [3]:
np.random.seed(50)
marks = np.random.randint(35,101,size=(7,7))
print(marks)

[[83 46 68 39 57 40 37]
 [70 61 41 55 78 66 84]
 [76 99 41 54 37 65 70]
 [61 95 37 45 86 35 35]
 [46 65 61 86 63 59 81]
 [97 48 71 35 93 78 99]
 [54 93 80 36 96 44 64]]


In [4]:
marks.ndim

2

In [6]:
marks.size

49

In [7]:
marks.shape

(7, 7)

In [8]:
marks.dtype

dtype('int64')

Module 2

In [9]:
import numpy as np

# Example: Student IDs from 1 to 7
student_ids = np.arange(1, 8)
print("Student IDs:", student_ids)

# Example: Marks from 35 to 100 with step 5
marks_range = np.arange(35, 101, 5)
print("Marks range:", marks_range)


Student IDs: [1 2 3 4 5 6 7]
Marks range: [ 35  40  45  50  55  60  65  70  75  80  85  90  95 100]
