A comprehensive interactive Jupyter notebook demonstrating NumPy fundamentals through a practical student marks management system. This educational project covers array operations, statistical analysis, and data manipulation using real-world scenarios.

In [45]:
import numpy as np

Data Creation

In [46]:
students = np.array(["A", "B", "C", "D", "E"])
subjects = np.array(["Math", "Science", "English", "History"])

marks = np.array([
    [85, 78, 92, 88],
    [72, 69, 75, 80],
    [90, 95, 85, 92],
    [60, 70, 65, 68],
    [88, 82, 79, 91]
])

print("Students:", students)
print("Subjects:", subjects)
print("Marks:\n", marks)


Students: ['A' 'B' 'C' 'D' 'E']
Subjects: ['Math' 'Science' 'English' 'History']
Marks:
 [[85 78 92 88]
 [72 69 75 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]


Data Exploration

In [47]:
print("For Students Array: ")
print("Shape of Marks Array:", students.shape)
print("Size of Marks Array:", students.size)
print("Dimensions:", students.ndim)
print("Data Type:", students.dtype)
print("\n")

print("For Subjects Array: ")
print("Shape of Marks Array:", subjects.shape)
print("Size of Marks Array:", subjects.size)
print("Dimensions:", subjects.ndim)
print("Data Type:", subjects.dtype)
print("\n")

print("For Marks Array: ")
print("Shape of Marks Array:", marks.shape)
print("Size of Marks Array:", marks.size)
print("Dimensions:", marks.ndim)
print("Data Type:", marks.dtype)


For Students Array: 
Shape of Marks Array: (5,)
Size of Marks Array: 5
Dimensions: 1
Data Type: <U1


For Subjects Array: 
Shape of Marks Array: (4,)
Size of Marks Array: 4
Dimensions: 1
Data Type: <U7


For Marks Array: 
Shape of Marks Array: (5, 4)
Size of Marks Array: 20
Dimensions: 2
Data Type: int64


Data Transformation

In [48]:
reshaped_marks = marks.T
print("Reshaped (Transposed) Marks:\n", reshaped_marks)

flat_marks = marks.flatten()
print("Flattened Marks:", flat_marks)

ravel_marks = marks.ravel()
print("Ravel Marks:", ravel_marks)


Reshaped (Transposed) Marks:
 [[85 72 90 60 88]
 [78 69 95 70 82]
 [92 75 85 65 79]
 [88 80 92 68 91]]
Flattened Marks: [85 78 92 88 72 69 75 80 90 95 85 92 60 70 65 68 88 82 79 91]
Ravel Marks: [85 78 92 88 72 69 75 80 90 95 85 92 60 70 65 68 88 82 79 91]


Data Combination

In [49]:
new_student_marks = np.array([[77, 85, 80, 79]])
updated_marks = np.vstack((marks, new_student_marks))
print("After Adding New Student:\n", updated_marks)

new_subject = np.array([[90], [85], [88], [70], [92], [81]])
marks_with_new_subject = np.hstack((updated_marks, new_subject))
print("After Adding New Subject:\n", marks_with_new_subject)

print("Shape of marks_with_new_subject:", marks_with_new_subject.shape)

split_arrays = np.hsplit(marks_with_new_subject, [2])
print("Split Arrays:\n", split_arrays[0], "\n and \n", split_arrays[1])

After Adding New Student:
 [[85 78 92 88]
 [72 69 75 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]
 [77 85 80 79]]
After Adding New Subject:
 [[85 78 92 88 90]
 [72 69 75 80 85]
 [90 95 85 92 88]
 [60 70 65 68 70]
 [88 82 79 91 92]
 [77 85 80 79 81]]
Shape of marks_with_new_subject: (6, 5)
Split Arrays:
 [[85 78]
 [72 69]
 [90 95]
 [60 70]
 [88 82]
 [77 85]] 
 and 
 [[92 88 90]
 [75 80 85]
 [85 92 88]
 [65 68 70]
 [79 91 92]
 [80 79 81]]


Data Modification

In [50]:
marks[1, 2] = 89
print("Updated Marks for B (English):\n", marks)

unique_marks = np.unique(marks)
print("Unique Marks:", unique_marks)

marks_removed = np.delete(marks, 3)
print("After Removing D:\n", marks_removed)

flipped_marks = np.flip(marks)
print("Flipped Marks:\n", flipped_marks)


Updated Marks for B (English):
 [[85 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]
Unique Marks: [60 65 68 69 70 72 78 79 80 82 85 88 89 90 91 92 95]
After Removing D:
 [85 78 92 72 69 89 80 90 95 85 92 60 70 65 68 88 82 79 91]
Flipped Marks:
 [[91 79 82 88]
 [68 65 70 60]
 [92 85 95 90]
 [80 89 69 72]
 [88 92 78 85]]






Data Type Handling

In [51]:
print("Converting marks to float")
marks_float = marks.astype(float)
print("Float Marks Array:\n", marks_float)
print("Data Type after conversion:", marks_float.dtype)

print("\n")
print("Back to integer")
marks_int = marks_float.astype(int)
print("Integer Marks Array:\n", marks_int)


Converting marks to float
Float Marks Array:
 [[85. 78. 92. 88.]
 [72. 69. 89. 80.]
 [90. 95. 85. 92.]
 [60. 70. 65. 68.]
 [88. 82. 79. 91.]]
Data Type after conversion: float64


Back to integer
Integer Marks Array:
 [[85 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]


Copy and View Behaviour

In [52]:
marks_copy = marks.copy()
marks_copy[0, 0] = 0
print("Original Marks before copy modification:\n", marks)
print("Copy Array:\n", marks_copy)

marks_view = marks.view()
marks_view[0, 0] = 99
print("Original Marks before view modification:\n", marks)
print("View Array:\n", marks_view)


Original Marks before copy modification:
 [[85 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]
Copy Array:
 [[ 0 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]
Original Marks before view modification:
 [[99 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]
View Array:
 [[99 78 92 88]
 [72 69 89 80]
 [90 95 85 92]
 [60 70 65 68]
 [88 82 79 91]]
